GET https://fullstackopen-helsinki-hqmt.onrender.com/api/persons
###
GET https://fullstackopen-helsinki-hqmt.onrender.com/info
###
DELETE https://fullstackopen-helsinki-hqmt.onrender.com/api/persons/1
###
POST https://fullstackopen-helsinki-hqmt.onrender.com/api/persons
Content-Type: application/json

{
  "name": "jackfruit",
  "number": "040-987654"
}